services:
  app:
    build: .
    ports:
      - "${PORT:-3030}:${PORT:-3030}"
    environment:
      - PORT=${PORT:-3030}
      - SECRET=${SECRET}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: